# Site settings
baseurl = "https://www.vr.umd.edu"
languageCode = "en-us"
title = "UMD VR"

googleAnalytics = ""

[params]
  name = "UMD VR Club"
  description = "The University of Maryland’s Virtual Reality Club is composed of students who share an interest in virtual and augmented reality. Come join us today!"

  favicon    = "favicon.ico"

  disableFonts = false

  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

    # Navigation
  [params.navigation]
    brand = "UMD VR"
    lab = "Lab"
    about = "About"
    projects = "Classes"
    team = "Team"
    contact = "Contact"

    [[menu.postpend]]
      url = "http://gohugo.io"
      name = "External link"
      weight = 10


  # Hero section
  [params.hero]
    title = "The University of Maryland, College Park"
    subtitle = "Virtual Reality Club"
    buttonText = "Join Now"


  # lab section
  [params.lab]
    enable = true
    title = "The Lab"
    subtitle = "Our lab has tons of cool gear, including Oculus Rifts, and the HTC vive. Find us on the fourth floor of A.V Williams!"

    [[params.lab.row]]

    [[params.lab.row.list]]
      title = "Hours"
      description = "Our lab hours change every day, so for now you can find out if we're open on our [Facebook page.](https://www.facebook.com/groups/UMDVRClub/) A lab hours module will be coming to this site soon!"
      url = "https://www.facebook.com/groups/UMDVRClub/"

    [[params.lab.row.list]]
      title = "Location"
      description = "Find us at Room 4176 of the A.V Williams Building at the University of Maryland, College Park. Here are the [directions on Google Maps.](https://www.google.com/maps/dir//A.V.+Williams+Bldg,+8223+Paint+Branch+Dr,+College+Park,+MD+20740/)"
      url = "https://www.google.com/maps/dir//A.V.+Williams+Bldg,+8223+Paint+Branch+Dr,+College+Park,+MD+20740/"

    [[params.lab.row.list]]
      title = "Virtual Tour"
      description = "Check out a 360 [holo-view of our lab!](https://www.flickr.com/photos/151895069@N03/32653511931/in/dateposted-public/) This was taken with the Ricoh 360° camera, which is available for use at the lab."
      url = "https://holobuilder.com/app/index.html?e=0&p=5277973575892992#player/5277973575892992?options=17"

  # projects section
  [params.projects]
    enable = true
    title = "classes"
    subtitle = "Here are our courses for the Spring 2017 semester!"

    [params.projects.modal]
      client = "Prerequisites"
      date = "Status"
      category = "Category"
      buttonText = "Exit class"


    # About section
  [params.about]
    enable = true
    title = "About Us"
    description = "The University of Maryland’s Virtual Reality Club was founded in 2014, and has since \
    grown to an organization with over 500+ student members. \
    We have VR resources \
    including Oculus Rifts and the HTC Vive, available to all members \
     in the lab. We host VR development classes, as well as smaller workshops where you can \
     learn about VR in our newly launched small-group mentorship program. \
     We cover topics in our classes like learning to use Unity and Unreal, as well as creating art optimized for VR. \
     Our ultimate mission is to work with the \
     community to develop a great VR culture for students, research, and startups at the University of Maryland."

    # The about timeline is NOT configurable under hugo, it is hardcoded in layouts
  
	# Team section
  [params.team]
    enable = true
    title = "Our team"
    description = "The VR club is lead by a team of motivated students with a variety of skills and backgrounds, and a common passion for virtual reality development."

    # ["fa-twitter", "#"],
    # ["fa-facebook", "#"],
    # ["fa-linkedin", "#"]

    [[params.team.members]]
      name = "Amitabh Varshney"
      position = "Advisor"
      social = []

    [[params.team.members]]
      name = "Mikhail Sorokin"
      position = "President"
      social = []

    [[params.team.members]]
      name = "Harrison Linowes"
      position = "Vice President"
      social = []

    [[params.team.members]]
      name = "Richard Vook"
      position = "Treasurer"
      social = []

    [[params.team.members]]
      name = "Darpan Shah"
      position = "Outreach Treasurer"
      social = []

    [[params.team.members]]
      name = "Raghav Gupta (R.K.)"
      position = "Secretary"
      social = []

    [[params.team.members]]
      name = "Brandon Stoekel"
      position = "Resource Manager"
      social = []

    [[params.team.members]]
      name = "Eashaan Kumar"
      position = "Resource Manager"
      social = []

    [[params.team.members]]
      name = "Abhinav Bahl"
      position = "Resource Manager"
      social = []

    [[params.team.members]]
      name = "Mike Bartner"
      position = "Social Media Director"
      social = []

    [[params.team.members]]
      name = "Jack Bundra"
      position = "Event Manager"
      social = []

    [[params.team.members]]
      name = "Ishan Babbar"
      position = "Event Manager"
      social = []

    [[params.team.members]]
      name = "Bill Heberer"
      position = "Event Manager"
      social = []

    [[params.team.members]]
      name = "Kevin Chen"
      position = "Design Director"
      social = []

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "Get in touch with us at umdvrclub@gmail.com!"
    buttonText = "Send your message"

    email = "umdvrclub@gmail.com"

	#TODO: Clean this up
    [params.contact.form.name]
      text = "Name"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Email"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Phone"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Message"
      warning = "Please enter a message."

  # Footer section
  [params.footer]
    enable = true
    copyright = "Developed by Kevin Chen (2017)"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/UMDVRClub"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/umdvrclub/"

    [[params.footer.quicklinks]]
      text = "Member Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Other CS Clubs"
      link = "https://undergrad.cs.umd.edu/clubs-and-organizations"
