# Site settings
baseurl = "http://umdvr.com"
languageCode = "en-us"
title = "UMD VR"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "UMD VR Club"
  description = "The University of Maryland’s Virtual Reality Club is composed of students who share an interest in virtual and augmented reality. Come join us today!"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "UMD VR"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    lab = "Lab"
    about = "About"
    projects = "Classes"
    team = "Team"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://gohugo.io"
      name = "External link"
      weight = 10


  # Hero section
  [params.hero]
    title = "The University of Maryland, College Park"
    subtitle = "Virtual Reality Club"
    buttonText = "Join Now"


  # lab section
  [params.lab]
    enable = true
    title = "The Lab"
    subtitle = "Our lab has tons of cool gear, including Oculus Rifts, and the HTC vive. Find us on the fourth floor of A.V Williams!"

    [[params.lab.row]]

    [[params.lab.row.list]]
      title = "Hours"
      description = "Our lab hours change every day, so for now you can find out if we're open on our [Facebook page.](https://www.facebook.com/groups/UMDVRClub/) A lab hours module will be coming to this site soon!"
      url = "https://www.facebook.com/groups/UMDVRClub/"

    [[params.lab.row.list]]
      title = "Location"
      description = "Find us at Room 4176 of the A.V Williams Building at the University of Maryland, College Park. Here are the [directions on Google Maps.](https://www.google.com/maps/dir//A.V.+Williams+Bldg,+8223+Paint+Branch+Dr,+College+Park,+MD+20740/)"
      url = "https://www.google.com/maps/dir//A.V.+Williams+Bldg,+8223+Paint+Branch+Dr,+College+Park,+MD+20740/"

    [[params.lab.row.list]]
      title = "Virtual Tour"
      description = "Check out a 360 [holo-view of our lab!](https://www.flickr.com/photos/151895069@N03/32653511931/in/dateposted-public/) This was taken with the Ricoh 360° camera, which is available for use at the lab."
      url = "https://holobuilder.com/app/index.html?e=0&p=5277973575892992#player/5277973575892992?options=17"

  # projects section
  [params.projects]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "classes"
    subtitle = "Here are our courses for the Spring 2017 semester!"

    [params.projects.modal]
      client = "Prerequisites"
      date = "Status"
      category = "Category"
      buttonText = "Exit class"


    # About section
  [params.about]
    enable = true
    title = "About Us"
    description = "The University of Maryland’s Virtual Reality Club was founded in 2014, and has since \
    grown to an organization with over 500+ student members. \
    We have VR resources \
    including Oculus Rifts and the HTC Vive, available to all members \
     in the lab. We host VR development classes, as well as smaller workshops where you can \
     learn about VR in our newly launched small-group mentorship program. \
     We cover topics in our classes like learning to use Unity and Unreal, as well as creating art optimized for VR. \
     Our ultimate mission is to work with the \
     community to develop a great VR culture for students, research, and startups at the University of Maryland."

    # The about timeline is NOT configurable under hugo, it is hardcoded in layouts
  
	# Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Our team"
    description = "The VR club is lead by a team of motivated students with a variety of skills and backgrounds, and a common passion for virtual reality development."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    # img = "loh.jpg"
    # ["fa-twitter", "#"],
    # ["fa-facebook", "#"],
    # ["fa-linkedin", "#"]

    [[params.team.members]]
      name = "Amitabh Varshney"
      position = "Advisor"
      social = []

    [[params.team.members]]
      name = "Mikhail Sorokin"
      position = "President"
      social = []

    [[params.team.members]]
      name = "Harrison Linowes"
      position = "Vice President"
      social = []

    [[params.team.members]]
      name = "Richard Vook"
      position = "Treasurer"
      social = []

    [[params.team.members]]
      name = "Darpan Shah"
      position = "Outreach Treasurer"
      social = []

    [[params.team.members]]
      name = "Raghav Gupta (R.K.)"
      position = "Secretary"
      social = []

    [[params.team.members]]
      name = "Brandon Stoekel"
      position = "Resource Manager"
      social = []

    [[params.team.members]]
      name = "Eeashan Kumar"
      position = "Resource Manager"
      social = []

    [[params.team.members]]
      name = "Abhinav Bahl"
      position = "Resource Manager"
      social = []

    [[params.team.members]]
      name = "Mike Bartner"
      position = "Social Media Director"
      social = []

    [[params.team.members]]
      name = "Jack Bundra"
      position = "Event Manager"
      social = []

    [[params.team.members]]
      name = "Ishaan Babar"
      position = "Event Manager"
      social = []

    [[params.team.members]]
      name = "Bill Heberer"
      position = "Event Manager"
      social = []

    [[params.team.members]]
      name = "Kevin Chen"
      position = "Design Director"
      social = []

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "Get in touch with us!"
    buttonText = "Send your message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "umdvrclub@gmail.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Name"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Email"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Phone"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Message"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Developed by Kevin Chen (2017)"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/UMDVRClub"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/umdvrclub/"

    [[params.footer.quicklinks]]
      text = "Member Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Other CS Clubs"
      link = "https://undergrad.cs.umd.edu/clubs-and-organizations"
